# Generated by Django 6.0 on 2026-01-10 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('report_date', models.DateField(unique=True)),
                ('overall_conclusion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketBreadth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advancing', models.PositiveIntegerField()),
                ('declining', models.PositiveIntegerField()),
                ('advance_decline_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_breadth', to='posts.marketreport')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionalFlowAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.TextField()),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institutional_analysis', to='posts.marketreport')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionalFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_type', models.CharField(choices=[('FII', 'FII'), ('DII', 'DII')], max_length=10)),
                ('cash_market', models.DecimalField(decimal_places=2, max_digits=12)),
                ('futures', models.DecimalField(decimal_places=2, max_digits=12)),
                ('options', models.DecimalField(decimal_places=2, max_digits=12)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutional_flows', to='posts.marketreport')),
            ],
        ),
        migrations.CreateModel(
            name='IndianMarketIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_name', models.CharField(max_length=100)),
                ('prev_close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trend', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indian_indices', to='posts.marketreport')),
            ],
        ),
        migrations.CreateModel(
            name='IndianMarketAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.TextField()),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indian_analysis', to='posts.marketreport')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalMarketIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_name', models.CharField(max_length=100)),
                ('prev_close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trend', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_indices', to='posts.marketreport')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalMarketAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.TextField()),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='global_analysis', to='posts.marketreport')),
            ],
        ),
        migrations.CreateModel(
            name='SectorAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.TextField()),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sector_analysis', to='posts.marketreport')),
            ],
        ),
        migrations.CreateModel(
            name='SectorPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('gainer', 'Gainer'), ('loser', 'Loser')], max_length=10)),
                ('sector_name', models.CharField(max_length=100)),
                ('change_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_performance', to='posts.marketreport')),
            ],
        ),
        migrations.CreateModel(
            name='StockMover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('gainer', 'Gainer'), ('loser', 'Loser')], max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('prev_close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('volume', models.CharField(max_length=50)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movers', to='posts.marketreport')),
            ],
        ),
        migrations.CreateModel(
            name='StockMoverAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.TextField()),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_mover_analysis', to='posts.marketreport')),
            ],
        ),
    ]
