# Generated by Django 6.0 on 2026-01-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketreport',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
