# Generated by Django 6.0 on 2026-06-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_optionchainsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='MoneyGreeks Team', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_designation',
            field=models.CharField(default='Market Analyst', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='key_highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.JSONField(default=list, help_text='Array of content blocks (h1, paragraph, image)'),
        ),
        migrations.AlterField(
            model_name='globalmarketindex',
            name='change',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='globalmarketindex',
            name='change_percent',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
