# Generated by Django 6.0 on 2026-06-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_blogpost_author_blogpost_author_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('education', 'Education'), ('news', 'News')], max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
