# Generated by Django 6.0 on 2026-06-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_educationcategory_blogpost_education_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='news_placement',
            field=models.CharField(blank=True, choices=[('hero', 'Featured Hero'), ('latest', 'Latest Intelligence'), ('deep_dive', 'Deep Dive Analysis'), ('breaking', 'Breaking News'), ('live_feed', 'Live Feed'), ('quick_hit', 'Quick Hit')], max_length=50, null=True),
        ),
    ]
