# Generated by Django 6.0 on 2026-06-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_blogpost_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('bullish_votes', models.PositiveIntegerField(default=0)),
                ('bearish_votes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
