# Generated by Django 6.0 on 2026-06-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMarketReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('report_date', models.DateField(unique=True)),
                ('analyst', models.CharField(default='Jose C S', max_length=100)),
                ('analyst_designation', models.CharField(default='Founder & Head Analyst, MoneyGreeks', max_length=200)),
                ('overall_conclusion', models.TextField(blank=True)),
                ('report_data', models.JSONField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Post-Market Report',
                'verbose_name_plural': 'Post-Market Reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
