# Generated by Django 6.0 on 2026-06-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_blogpost_meta_description_blogpost_meta_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveMarketIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percent_change', models.DecimalField(decimal_places=2, max_digits=6)),
                ('up', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
