# Generated by Django 6.0 on 2026-06-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_livemarketindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbreadth',
            name='unchanged',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
