# Generated by Django 6.0 on 2026-06-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_marketbreadth_unchanged'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('rate_limited', 'Rate Limited')], default='ok', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('is_failing', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='marketbreadth',
            name='unchanged',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
