# Generated by Django 6.0 on 2026-06-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_apisystemlog_alter_marketbreadth_unchanged'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('blog_post', 'Blog Post'), ('market_report', 'Pre-Market Report'), ('post_market', 'Post-Market Report'), ('education', 'Education Article'), ('news_today', 'News Today'), ('home', 'Home'), ('blog', 'Blog'), ('archive', 'Archive'), ('other', 'Other')], default='other', max_length=30)),
                ('page_slug', models.CharField(blank=True, db_index=True, max_length=255)),
                ('page_title', models.CharField(blank=True, max_length=500)),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.CharField(blank=True, max_length=1000)),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
                ('bot_name', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('country_code', models.CharField(blank=True, max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['page_type', 'created_at'], name='posts_pagev_page_ty_d7e3e8_idx'), models.Index(fields=['page_type', 'page_slug', 'created_at'], name='posts_pagev_page_ty_8f44e2_idx'), models.Index(fields=['is_bot', 'created_at'], name='posts_pagev_is_bot_481019_idx')],
            },
        ),
    ]
